// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx'
import * as $_app from './routes/_app.tsx'
import * as $_middleware from './routes/_middleware.ts'
import * as $auditions_index from './routes/auditions/index.tsx'
import * as $auditions_thankyou from './routes/auditions/thankyou.tsx'
import * as $index from './routes/index.tsx'
import * as $media_path_ from './routes/media/[...path].ts'
import * as $partials_auditions from './routes/partials/auditions.tsx'
import * as $partials_bio from './routes/partials/bio.tsx'
import * as $partials_contact from './routes/partials/contact.tsx'
import * as $partials_home from './routes/partials/home.tsx'
import * as $partials_links from './routes/partials/links.tsx'
import * as $partials_shows from './routes/partials/shows.tsx'
import * as $ActionZoneController from './islands/ActionZoneController.tsx'
import * as $ContentPageOrchestrator from './islands/ContentPageOrchestrator.tsx'
import * as $DebugControls from './islands/DebugControls.tsx'
import * as $DebugPanels from './islands/DebugPanels.tsx'
import * as $FormManager from './islands/FormManager.tsx'
import * as $Header from './islands/Header.tsx'
import * as $PageManager from './islands/PageManager.tsx'
import * as $ThemeProvider from './islands/ThemeProvider.tsx'
import * as $ThemedBackground from './islands/ThemedBackground.tsx'
import type { Manifest } from '$fresh/server.ts'

const manifest = {
  routes: {
    './routes/_404.tsx': $_404,
    './routes/_app.tsx': $_app,
    './routes/_middleware.ts': $_middleware,
    './routes/auditions/index.tsx': $auditions_index,
    './routes/auditions/thankyou.tsx': $auditions_thankyou,
    './routes/index.tsx': $index,
    './routes/media/[...path].ts': $media_path_,
    './routes/partials/auditions.tsx': $partials_auditions,
    './routes/partials/bio.tsx': $partials_bio,
    './routes/partials/contact.tsx': $partials_contact,
    './routes/partials/home.tsx': $partials_home,
    './routes/partials/links.tsx': $partials_links,
    './routes/partials/shows.tsx': $partials_shows,
  },
  islands: {
    './islands/ActionZoneController.tsx': $ActionZoneController,
    './islands/ContentPageOrchestrator.tsx': $ContentPageOrchestrator,
    './islands/DebugControls.tsx': $DebugControls,
    './islands/DebugPanels.tsx': $DebugPanels,
    './islands/FormManager.tsx': $FormManager,
    './islands/Header.tsx': $Header,
    './islands/PageManager.tsx': $PageManager,
    './islands/ThemeProvider.tsx': $ThemeProvider,
    './islands/ThemedBackground.tsx': $ThemedBackground,
  },
  baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
