// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx'
import * as $_app from './routes/_app.tsx'
import * as $bio from './routes/bio.tsx'
import * as $contact from './routes/contact.tsx'
import * as $index from './routes/index.tsx'
import * as $shows from './routes/shows.tsx'
import * as $BottomNav from './islands/BottomNav.tsx'
import * as $Home from './islands/Home.tsx'
import * as $MusicPlayer from './islands/MusicPlayer.tsx'
import type { Manifest } from '$fresh/server.ts'

const manifest = {
  routes: {
    './routes/_404.tsx': $_404,
    './routes/_app.tsx': $_app,
    './routes/bio.tsx': $bio,
    './routes/contact.tsx': $contact,
    './routes/index.tsx': $index,
    './routes/shows.tsx': $shows,
  },
  islands: {
    './islands/BottomNav.tsx': $BottomNav,
    './islands/Home.tsx': $Home,
    './islands/MusicPlayer.tsx': $MusicPlayer,
  },
  baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
