import { type Config } from 'tailwindcss'

const themeColor = (variable: string) => `var(--colors-${variable})`
const fontFamily = (variable: string) => `var(--typography-fontFamily-${variable})`
const glass = (variable: string) => `var(--glass-${variable})`
const frost = (variable: string) => `var(--frost-${variable})`
const borderRadius = (variable: string) => `var(--borderRadius-${variable})`
const filter = (variable: string) => `var(--filters-${variable})`
const surface = (type: string, property: string) => `var(--surfaces-${type}-${property})`

export default {
  content: [
    '{routes,islands,components}/**/*.{ts,tsx,js,jsx}',
    './static/styles.css',
  ],
  theme: {
    extend: {
      colors: {
        background: {
          primary: themeColor('background-primary'),
          secondary: themeColor('background-secondary'),
          tertiary: themeColor('background-tertiary'),
        },
        surface: {
          primary: themeColor('surface-primary'),
          secondary: themeColor('surface-secondary'),
          elevated: themeColor('surface-elevated'),
          main: surface('main', 'background'),
          alt: surface('alt', 'background'),
          header: surface('header', 'background'),
          nav: surface('nav', 'background'),
          card: surface('card', 'background'),
          input: surface('input', 'background'),
          button: surface('button', 'background'),
          dropdown: surface('dropdown', 'background'),
        },
        text: {
          primary: themeColor('text-primary'),
          secondary: themeColor('text-secondary'),
          tertiary: themeColor('text-tertiary'),
          inverse: themeColor('text-inverse'),
        },
        border: {
          primary: themeColor('border-primary'),
          secondary: themeColor('border-secondary'),
          focus: themeColor('border-focus'),
          main: surface('main', 'borderColor'),
          alt: surface('alt', 'borderColor'),
          header: surface('header', 'borderColor'),
          nav: surface('nav', 'borderColor'),
          card: surface('card', 'borderColor'),
          input: surface('input', 'borderColor'),
          button: surface('button', 'borderColor'),
          dropdown: surface('dropdown', 'borderColor'),
        },
        interactive: {
          primary: themeColor('interactive-primary'),
          primaryHover: themeColor('interactive-primaryHover'),
          secondary: themeColor('interactive-secondary'),
          secondaryHover: themeColor('interactive-secondaryHover'),
          ghost: themeColor('interactive-ghost'),
          ghostHover: themeColor('interactive-ghostHover'),
          ghostActive: themeColor('interactive-ghostActive'),
        },
      },
      backgroundColor: {
        glass: glass('background'),
        frost: frost('background'),
        'surface-main': surface('main', 'background'),
        'surface-alt': surface('alt', 'background'),
        'surface-header': surface('header', 'background'),
        'surface-nav': surface('nav', 'background'),
        'surface-card': surface('card', 'background'),
        'surface-input': surface('input', 'background'),
        'surface-button': surface('button', 'background'),
        'surface-dropdown': surface('dropdown', 'background'),
      },
      borderColor: {
        glass: glass('border'),
        frost: frost('border'),
        'surface-main': surface('main', 'borderColor'),
        'surface-alt': surface('alt', 'borderColor'),
        'surface-header': surface('header', 'borderColor'),
        'surface-nav': surface('nav', 'borderColor'),
        'surface-card': surface('card', 'borderColor'),
        'surface-input': surface('input', 'borderColor'),
        'surface-button': surface('button', 'borderColor'),
        'surface-dropdown': surface('dropdown', 'borderColor'),
      },
      backdropBlur: {
        glass: glass('backdrop'),
        frost: frost('backdrop'),
        'surface-main': surface('main', 'backdropBlur'),
        'surface-alt': surface('alt', 'backdropBlur'),
        'surface-header': surface('header', 'backdropBlur'),
        'surface-nav': surface('nav', 'backdropBlur'),
        'surface-card': surface('card', 'backdropBlur'),
        'surface-input': surface('input', 'backdropBlur'),
        'surface-button': surface('button', 'backdropBlur'),
        'surface-dropdown': surface('dropdown', 'backdropBlur'),
      },
      borderRadius: {
        'theme-none': borderRadius('none'),
        'theme-sm': borderRadius('sm'),
        'theme-md': borderRadius('md'),
        'theme-lg': borderRadius('lg'),
        'theme-xl': borderRadius('xl'),
        'theme-full': borderRadius('full'),
        'surface-main': surface('main', 'borderRadius'),
        'surface-alt': surface('alt', 'borderRadius'),
        'surface-header': surface('header', 'borderRadius'),
        'surface-nav': surface('nav', 'borderRadius'),
        'surface-card': surface('card', 'borderRadius'),
        'surface-input': surface('input', 'borderRadius'),
        'surface-button': surface('button', 'borderRadius'),
        'surface-dropdown': surface('dropdown', 'borderRadius'),
      },
      filter: {
        'main': filter('main'),
        'header': filter('header'),
        'nav': filter('nav'),
        'surface-main': surface('main', 'filter'),
        'surface-alt': surface('alt', 'filter'),
        'surface-header': surface('header', 'filter'),
        'surface-nav': surface('nav', 'filter'),
        'surface-card': surface('card', 'filter'),
        'surface-input': surface('input', 'filter'),
        'surface-button': surface('button', 'filter'),
        'surface-dropdown': surface('dropdown', 'filter'),
      },
      boxShadow: {
        'surface-main': surface('main', 'boxShadow'),
        'surface-alt': surface('alt', 'boxShadow'),
        'surface-header': surface('header', 'boxShadow'),
        'surface-nav': surface('nav', 'boxShadow'),
        'surface-card': surface('card', 'boxShadow'),
        'surface-input': surface('input', 'boxShadow'),
        'surface-button': surface('button', 'boxShadow'),
        'surface-dropdown': surface('dropdown', 'boxShadow'),
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeOut: {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
      },
      animation: {
        fadeIn: 'fadeIn 0.3s ease-in-out',
        fadeOut: 'fadeOut 0.3s ease-in-out',
      },
      fontFamily: {
        heading: fontFamily('heading'),
        sans: fontFamily('body'),
        quote: fontFamily('quote'),
      },
    },
  },
  plugins: [
    function ({ addUtilities }: { addUtilities: any }) {
      addUtilities({
        '.surface-main': {
          'background-color': surface('main', 'background'),
          'border-color': surface('main', 'borderColor'),
          'border-radius': surface('main', 'borderRadius'),
          'backdrop-filter': surface('main', 'backdropBlur'),
          'box-shadow': surface('main', 'boxShadow'),
          'filter': surface('main', 'filter'),
        },
        '.surface-alt': {
          'background-color': surface('alt', 'background'),
          'border-color': surface('alt', 'borderColor'),
          'border-radius': surface('alt', 'borderRadius'),
          'backdrop-filter': surface('alt', 'backdropBlur'),
          'box-shadow': surface('alt', 'boxShadow'),
          'filter': surface('alt', 'filter'),
        },
        '.surface-header': {
          'background-color': surface('header', 'background'),
          'border-color': surface('header', 'borderColor'),
          'border-radius': surface('header', 'borderRadius'),
          'backdrop-filter': surface('header', 'backdropBlur'),
          'box-shadow': surface('header', 'boxShadow'),
          'filter': surface('header', 'filter'),
        },
        '.surface-nav': {
          'background-color': surface('nav', 'background'),
          'border-color': surface('nav', 'borderColor'),
          'border-radius': surface('nav', 'borderRadius'),
          'backdrop-filter': surface('nav', 'backdropBlur'),
          'box-shadow': surface('nav', 'boxShadow'),
          'filter': surface('nav', 'filter'),
        },
        '.surface-card': {
          'background-color': surface('card', 'background'),
          'border-color': surface('card', 'borderColor'),
          'border-radius': surface('card', 'borderRadius'),
          'backdrop-filter': surface('card', 'backdropBlur'),
          'box-shadow': surface('card', 'boxShadow'),
          'filter': surface('card', 'filter'),
        },
        '.surface-input': {
          'background-color': surface('input', 'background'),
          'border-color': surface('input', 'borderColor'),
          'border-radius': surface('input', 'borderRadius'),
          'backdrop-filter': surface('input', 'backdropBlur'),
          'box-shadow': surface('input', 'boxShadow'),
          'filter': surface('input', 'filter'),
        },
        '.surface-button': {
          'background-color': surface('button', 'background'),
          'border-color': surface('button', 'borderColor'),
          'border-radius': surface('button', 'borderRadius'),
          'backdrop-filter': surface('button', 'backdropBlur'),
          'box-shadow': surface('button', 'boxShadow'),
          'filter': surface('button', 'filter'),
        },
        '.surface-dropdown': {
          'background-color': surface('dropdown', 'background'),
          'border-color': surface('dropdown', 'borderColor'),
          'border-radius': surface('dropdown', 'borderRadius'),
          'backdrop-filter': surface('dropdown', 'backdropBlur'),
          'box-shadow': surface('dropdown', 'boxShadow'),
          'filter': surface('dropdown', 'filter'),
        },
      })
    },
  ],
} satisfies Config
