/**
 * Animation timing and visual effect parameters
 */
export const ANIMATION_CONFIG = {
  TIME_INCREMENT: 0.01,
  CHROMA_GLITCH_PROBABILITY: 0.002,
  CHROMA_GLITCH_INTENSITY_MIN: 2,
  CHROMA_GLITCH_INTENSITY_MAX: 5,
  CHROMA_GLITCH_RESET_DELAY: 120,
  BLOOM_PULSE_FREQUENCY: 0.8,
  BLOOM_PULSE_INTENSITY: 0.15,
}
